#!/usr/bin/env python3
"""Deep-merge a local overlay YAML file into a base resume YAML file.

Used to merge a gitignored, local-only overlay (e.g. containing a phone
number) into resume.yml before building a personal PDF with full contact
details, so the committed/public resume.yml and the public CI build stay
free of that private data.

Dicts are merged key-by-key, recursively; any other value in the overlay
(including lists) replaces the corresponding base value outright.

Usage: python3 scripts/merge_overlay.py <base.yml> <overlay.yml> <output.yml>
"""
import sys
from pathlib import Path

import yaml


def _literal_str_representer(dumper, data):
    style = "|" if "\n" in data else None
    return dumper.represent_scalar("tag:yaml.org,2002:str", data, style=style)


yaml.add_representer(str, _literal_str_representer)


def deep_merge(base, overlay):
    if isinstance(base, dict) and isinstance(overlay, dict):
        merged = dict(base)
        for key, value in overlay.items():
            merged[key] = deep_merge(base.get(key), value)
        return merged
    return overlay


def main() -> None:
    if len(sys.argv) != 4:
        sys.exit("usage: merge_overlay.py <base.yml> <overlay.yml> <output.yml>")

    base_path, overlay_path, out_path = (Path(p) for p in sys.argv[1:4])

    base = yaml.safe_load(base_path.read_text())
    overlay = yaml.safe_load(overlay_path.read_text()) or {}

    merged = deep_merge(base, overlay)

    out_path.write_text(
        "# Generated by scripts/merge_overlay.py from"
        f" {base_path.name} + {overlay_path.name} — do not edit directly.\n"
        "# yaml-language-server: $schema=https://yamlresume.dev/schema.json\n\n"
        + yaml.dump(merged, sort_keys=False, allow_unicode=True, width=1000)
    )


if __name__ == "__main__":
    main()
